language: python

sudo: false

os:
  - linux

python:
  - "3.8"

install:
  - pip install .[test]

script:

  - python setup.py check --restructuredtext

  - pip install pytest -U
  - pytest -rx --flake8 --cov baldrick baldrick

  # Install sphinx now - this is to make sure that the tests for baldrick don't
  # need sphinx or its dependencies to be installed
  - pip install sphinx sphinx-automodapi
  - cd doc
  - make html
  - cd ..

after_success:
    - codecov
